FROM amazoncorretto:11-alpine-jdk //de que imagen partimos(java)
MAINTAINER JV //dueño de imagen
COPY . /usr/src/myapp //va a copiar el epaquetado de github
ENTRYPOINT //la instruccion que se va a ejecutar primero